import "./globals.css";
import { Poppins } from "next/font/google";
import GlobalProvider from "@/components/hoc/GlobalProvider";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
